services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: grafana_db
      MYSQL_USER: grafana_user
      MYSQL_PASSWORD: grafana_password
    ports:
      - "3306:3306"
    volumes:
    - mysql-data:/var/lib/mysql

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - mysql

  backend:
    image: pichif/api:latest
    container_name: api
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      DB_USER: grafana_user
      DB_PASSWORD: grafana_password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: grafana_db
    privileged: true
    pid: host
    restart: always
    ports:
      - 4000:4000

volumes:
  mysql-data:
  grafana-data: