DROP TABLE IF EXISTS grafana_db.RAM, grafana_db.CPU;
CREATE TABLE IF NOT EXISTS grafana_db.RAM (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usado FLOAT,
    disponible FLOAT,
    tiempo DATETIME,
    pc INT
);

CREATE TABLE IF NOT EXISTS grafana_db.CPU (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usado FLOAT,
    disponible FLOAT,
    tiempo DATETIME,
    pc INT
);

CREATE TABLE IF NOT EXISTS grafana_db.PROCESOS (
    pid INT PRIMARY KEY,
    nombre VARCHAR(255),
    usuario VARCHAR(255),
    estado VARCHAR(255),
    ram_usada VARCHAR(255)
);

SELECT * FROM GRAFANA_DB.RAM;
SELECT * FROM GRAFANA_DB.CPU;

TRUNCATE TABLE GRAFANA_DB.RAM;
TRUNCATE TABLE GRAFANA_DB.CPU;